name: Wiki Sync

on:
  # 1. Déclenchement manuel quand tu pushes sur ce repo
  push:
    branches: [ main ]
    paths:
      - 'wiki/**'
      - '.github/acidwiki.json'               # <--- NOUVEAU CHEMIN
      - '.github/workflows/wiki-sync.yml'
  
  # 2. Bouton manuel dans l'interface Actions
  workflow_dispatch:

  # 3. AUTOMATIQUE : Tous les jours à 4h00 du matin (UTC)
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-wiki:
    uses: infinition/AcidWiki/.github/workflows/reusable-wiki-sync.yml@main
