name: Wiki Sync

on:
  push:
    branches: [ main ]
    paths:
      - 'wiki/**'
      - '.github/acidwiki.json'      # <-- Surveille ton fichier JSON auto-généré
      - '.github/workflows/wiki-sync.yml'
  
  workflow_dispatch:

  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: write   # OBLIGATOIRE : Autorise le workflow maître à te renvoyer le .json
  pages: write
  id-token: write

jobs:
  deploy-wiki:
    uses: infinition/AcidWiki/.github/workflows/reusable-wiki-sync.yml@main
